env:
  browser: true
  es2021: true
extends: airbnb-base/legacy
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  {
    implicit-arrow-linebreak: off,
    function-paren-newline: off,
    class-methods-use-this: off
  }
